# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b9acec5b1ea42b4b5fc6b1da3d430eeb824c29a6f6b2ae6a2e9e67c8725109f99214e2f2c75dfc20c95e5ec50467d98bcf47a1bb86c62562ca7daca7cc50a80

test:
  secret_key_base: cd31705714ed213104fe0ab17a96226e845079df6ed532c4cececa8502e32aa83883adaee7391983c31ab8cbdc839fdeac5fc6bef3f8eced8c28c882514fc58a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
